kind: Template
apiVersion: v1
template: images-data-loader
metadata:
  name: images-data-loader
objects:

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: ${JOB_NAME}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: ${JOB_NAME}
      spec:
        containers:
          - name: postgres 
            image: postgres:10.4
            env:
              - name: SERVER
                value: postgresql
              - name: DBNAME
                value: wineDb
              - name: USER
                value: username
              - name: PASSWORD
                value: password
        restartPolicy: OnFailure

parameters:
  - name: JOB_NAME
    from: "jdsl-[a-z0-9]{4}"
    generate: expression
    description: unique name for this job run
